-- Active: 1761903832511@@127.0.0.1@5432@cos101_db
SELECT version();

CREATE TABLE IF NOT EXISTS company (
    ID INT PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    AGE INT NOT NULL CHECK (AGE >= 0),
    ADDRESS CHAR(50),
    SALARY REAL,
    JOIN_DATE  DATE
);

CREATE TABLE IF NOT EXISTS departments (
    ID INT PRIMARY KEY NOT NULL,
    DEPT CHAR(50),
    EMP_ID INT NOT NULL
);

INSERT INTO company (ID, NAME, AGE, ADDRESS, SALARY, JOIN_DATE)
VALUES (1, 'Chuka', 32, 'Ebonyi', 2000.00, '2001-07-13');